#!/bin/sh
# Regenerates src/lectures/pdfData.ts from assets/lectures/*.pdf (base64, embedded so the web build is one file).
out=src/lectures/pdfData.ts
echo "// Generated by scripts-embed-pdfs.sh — do not edit by hand." > $out
echo "export const PDF_DATA: Record<string, string> = {" >> $out
for f in assets/lectures/*.pdf; do
  k=$(basename "$f" .pdf)
  printf "  '%s': '" "$k" >> $out
  base64 -i "$f" | tr -d '\n' >> $out
  printf "',\n" >> $out
done
echo "};" >> $out
